source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SegmentedControl_Example', :exclusive => true do
  pod 'SegmentedControl', :path => '../'
end

target 'SegmentedControl_Tests', :exclusive => true do
  pod 'SegmentedControl', :path => '../'

  
end
